[package]
name = "minidsp-volume-steps-rs"
version = "0.0.1"
authors = ["Niklas Carlsson <niklas.carlsson1994@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
num = "0.4.0"
regex = "1.4.5"
evdev-rs = "0.5.0"
